name: Node.js CI

on:
  push:
    branches: [ "main", "add-cypress-scripts" ]
  pull_request:
    branches: [ "main", "add-cypress-scripts" ]

jobs:
  build:
    runs-on: ubuntu-latest  # ✅ REQUIRED
    container: node:20  # ✅ Run inside the Node.js 20 Docker image

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and tag Docker image
      run: |
        docker build . -t ghcr.io/nishan-silva/dis-app:latest -t ghcr.io/nishan-silva/dis-app:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push ghcr.io/nishan-silva/dis-app:latest
        docker push ghcr.io/nishan-silva/dis-app:${{ github.sha }}
