name: Dis App CI

on:
  push:
    branches: [ "main", "add-cypress-scripts" ]
  pull_request:
    branches: [ "main", "add-cypress-scripts" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Build and tag Docker image
      run: docker build . -t ghcr.io/nishan-silva/dis-app:latest

    - name: Push Docker image
      run: docker push ghcr.io/nishan-silva/dis-app:latest
