name: DIS App CI/CD

on:
  push:
    branches: [ "main", "adding-cypress-to-ci-file" ]
  pull_request:
    branches: [ "main", "adding-cypress-to-ci-file" ]
  workflow_dispatch:

jobs:
  # build_dis_app:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Set up Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 20
  #       cache: 'npm'

  #   - name: Install dependencies
  #     run: npm ci

  #   - name: Log in to GitHub Container Registry
  #     uses: docker/login-action@v3
  #     with:
  #       registry: ghcr.io
  #       username: ${{ secrets.GHCR_USERNAME }}
  #       password: ${{ secrets.GHCR_TOKEN }}

  #   - name: Build and tag Docker image
  #     run: |
  #       docker build . \
  #         -t ghcr.io/nishan-silva/dis-app:latest \
  #         -t ghcr.io/nishan-silva/dis-app:${{ github.sha }}

  #   - name: Push Docker image
  #     run: |
  #       docker push ghcr.io/nishan-silva/dis-app:latest
  #       docker push ghcr.io/nishan-silva/dis-app:${{ github.sha }}
        
   end-to-end-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:11.0.0
    env:
      DIS_BASE_URL: ${{ secrets.DIS_BASE_URL }}  # Load environment variable from GitHub Secrets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress End-to-End Tests
        run: |
          echo "Running Cypress E2E tests..."
          npx cypress run --spec "cypress/e2e/**/*.cy.js"

      - name: Upload Cypress Test Results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/screenshots/
          retention-days: 5